/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HeaderListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheHeaderListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "ID" });
            Then.onTheHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "email" });
            Then.onTheHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "Createon" });
            Then.onTheHeaderListGenerated.onFilterBar().iCheckFilterField({ property: "OrderStatus_status" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheHeaderListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheHeaderListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheHeaderListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheHeaderListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheHeaderListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"ID":{"header":"Id"},"email":{"header":"Email"},"firstname":{"header":"First name"},"lastname":{"header":"Last name"},"Country":{"header":"Country"},"Createon":{"header":"Created on"},"deliverydate":{"header":"Delivery date"},"OrderStatus":{"header":"Status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHeaderListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheHeaderListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheHeaderObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});