/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HeaderObjectPageObjectPage journey");

        opaTest("Navigate to HeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHeaderListGenerated.onTable().iCheckRows();
            When.onTheHeaderListGenerated.onTable().iPressRow(0);

            Then.onTheHeaderObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheHeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::HeaderData" });
            Then.onTheHeaderObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "Createon",
                targetAnnotation: ""
            });
            Then.onTheHeaderObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "deliverydate",
                targetAnnotation: ""
            });
            Then.onTheHeaderObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "OrderStatus",
                targetAnnotation: "description"
            });
        });

        opaTest("Check the Facets::0 section of the Object Page", function (_Given, When, Then) {
            Then.onTheHeaderObjectPageGenerated.iCheckSection({ section: "Facets::0" });
            When.onTheHeaderObjectPageGenerated.iGoToSection({ section: "Facets::0", subSection: "FieldGroup::Detail" });
            Then.onTheHeaderObjectPageGenerated.iCheckSubSection({ section: "FieldGroup::Detail" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "FieldGroup::Detail" }).iCheckField({ property: "email" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "FieldGroup::Detail" }).iCheckField({ property: "firstname" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "FieldGroup::Detail" }).iCheckField({ property: "lastname" });
            Then.onTheHeaderObjectPageGenerated.onForm({ section: "FieldGroup::Detail" }).iCheckField({ property: "Country" });
            When.onTheHeaderObjectPageGenerated.iGoToSection({ section: "Facets::0", subSection: "items::LineItem" });
            Then.onTheHeaderObjectPageGenerated.iCheckSubSection({ section: "items::LineItem" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});