/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ItemsObjectPageObjectPage journey");

        opaTest("Navigate to ItemsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHeaderListGenerated.onTable().iCheckRows();
            When.onTheHeaderListGenerated.onTable().iPressRow(0);

            Then.onTheHeaderObjectPageGenerated.iSeeThisPage();
            Then.onTheHeaderObjectPageGenerated.onTable({ property: "items" }).iCheckRows();
            When.onTheHeaderObjectPageGenerated.onTable({ property: "items" }).iPressRow(0);

            Then.onTheItemsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the Facets::0 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheItemsObjectPageGenerated.iCheckSection({ section: "Facets::0" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Name" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Description" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "ReleaseDate" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "DiscontinuedDate" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Price" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Waers" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Quantity" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Unitofmeasure" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Height" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Width" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "Depth" });
            Then.onTheItemsObjectPageGenerated.onForm({ section: "Facets::0" }).iCheckField({ property: "DimensionsUOM" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});